spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ttibu
    username: tibutibu
    password: tibutibu
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

server:
  port: 8080
